runtime: nodejs10
service: react-dashboard
# service: preprod-react-dashboard

# [START handlers]
handlers:
# All files that can be compiled in angular. Luckily, they all have suffixes.
- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: build/\1
  upload: build/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

- url: /(.*)
  static_files: build/index.html
  upload: build/index.html

#- url: /(.*)
#  static_files: build
#  upload: build/(.*)
# [END handlers]